import {
  Activity,
  AlarmPlus as Alarm,
  Anchor,
  Apple,
  Award,
  Baby,
  Bike,
  Book,
  Brain,
  Brush,
  Camera,
  Car,
  Coffee,
  Compass,
  Cookie,
  Cpu,
  Crown,
  Diamond,
  Dumbbell,
  Eye,
  Fish,
  Flag,
  Flame,
  FlaskRound as Flask,
  Flower,
  FolderRoot as Football,
  Gift,
  Globe,
  Guitar,
  Heart,
  Home,
  Key,
  Lamp,
  Leaf,
  Library,
  CloudLightning as Lightning,
  Link,
  Mail,
  Map,
  Moon,
  Mountain,
  Music,
  Paintbrush as Paint,
  Palette,
  Pen,
  Phone,
  Piano,
  Plane,
} from "lucide-react";

export const habitIcons = [
  { icon: Activity, name: "Activity" },
  { icon: Alarm, name: "Alarm" },
  { icon: Anchor, name: "Anchor" },
  { icon: Apple, name: "Apple" },
  { icon: Award, name: "Award" },
  { icon: Baby, name: "Baby" },
  { icon: Bike, name: "Bike" },
  { icon: Book, name: "Book" },
  { icon: Brain, name: "Brain" },
  { icon: Brush, name: "Brush" },
  { icon: Camera, name: "Camera" },
  { icon: Car, name: "Car" },
  { icon: Coffee, name: "Coffee" },
  { icon: Compass, name: "Compass" },
  { icon: Cookie, name: "Cookie" },
  { icon: Cpu, name: "Cpu" },
  { icon: Crown, name: "Crown" },
  { icon: Diamond, name: "Diamond" },
  { icon: Dumbbell, name: "Dumbbell" },
  { icon: Eye, name: "Eye" },
  { icon: Fish, name: "Fish" },
  { icon: Flag, name: "Flag" },
  { icon: Flame, name: "Flame" },
  { icon: Flask, name: "Flask" },
  { icon: Flower, name: "Flower" },
  { icon: Football, name: "Football" },
  { icon: Gift, name: "Gift" },
  { icon: Globe, name: "Globe" },
  { icon: Guitar, name: "Guitar" },
  { icon: Heart, name: "Heart" },
  { icon: Home, name: "Home" },
  { icon: Key, name: "Key" },
  { icon: Lamp, name: "Lamp" },
  { icon: Leaf, name: "Leaf" },
  { icon: Library, name: "Library" },
  { icon: Lightning, name: "Lightning" },
  { icon: Link, name: "Link" },
  { icon: Mail, name: "Mail" },
  { icon: Map, name: "Map" },
  { icon: Moon, name: "Moon" },
  { icon: Mountain, name: "Mountain" },
  { icon: Music, name: "Music" },
  { icon: Paint, name: "Paint" },
  { icon: Palette, name: "Palette" },
  { icon: Pen, name: "Pen" },
  { icon: Phone, name: "Phone" },
  { icon: Piano, name: "Piano" },
  { icon: Plane, name: "Plane" },
];

export const habitColors = [
  { name: "Red", value: "#ef4444" },
  { name: "Orange", value: "#f97316" },
  { name: "Amber", value: "#f59e0b" },
  { name: "Yellow", value: "#eab308" },
  { name: "Lime", value: "#84cc16" },
  { name: "Green", value: "#22c55e" },
  { name: "Emerald", value: "#10b981" },
  { name: "Teal", value: "#14b8a6" },
  { name: "Cyan", value: "#06b6d4" },
  { name: "Sky", value: "#0ea5e9" },
  { name: "Blue", value: "#3b82f6" },
  { name: "Indigo", value: "#6366f1" },
  { name: "Violet", value: "#8b5cf6" },
  { name: "Purple", value: "#a855f7" },
  { name: "Fuchsia", value: "#d946ef" },
  { name: "Pink", value: "#ec4899" },
  { name: "Rose", value: "#f43f5e" },
  { name: "Slate", value: "#64748b" },
  { name: "Gray", value: "#6b7280" },
  { name: "Zinc", value: "#71717a" },
];

export const habitCategories = [
  "Health & Fitness",
  "Personal Development",
  "Work",
  "Relationships",
  "Hobbies & Creativity",
  "Finance",
  "Mental Wellbeing",
  "Education",
  "Home & Organization",
  "Social & Community",
];
