import {
  Activity,
  AlarmClock,
  AlarmClockCheck,
  Dumbbell,
  BicepsFlexed,
  Languages,
  CupSoda,
  Sprout,
  FlameKindling,
  Flower,
  Heart,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Wind,
  GlassWater,
  Footprints,
  LandPlot,
  CircleGauge,
  Medal,
  Trophy,
  Award,
  PersonStanding,
  Gamepad2,
  Skull,
  Flame,
  Book,
  BookA,
  BookOpen,
  Egg,
  Pizza,
  Receipt,
  DollarSign,
  BadgeDollarSign,
  BadgePoundSterling,
  CircleDollarSign,
  Wallet,
  ShowerHead,
  Brush,
  Apple,
  Baby,
  Bike,
  Brain,
  Camera,
  Car,
  Coffee,
  Compass,
  Cookie,
  Cpu,
  Crown,
  Diamond,
  Eye,
  Fish,
  Flag,
  FlaskRound as Flask,
  FolderRoot as Football,
  Gift,
  Globe,
  Guitar,
  Home,
  Key,
  Lamp,
  Leaf,
  Library,
  CloudLightning as Lightning,
  Link,
  Mail,
  Map,
  Moon,
  Mountain,
  Music,
  Paintbrush as Paint,
  Palette,
  Pen,
  Phone,
  Piano,
  Plane,
} from "lucide-react";

export const habitIcons = [
  { icon: Activity, name: "Activity" },
  { icon: AlarmClock, name: "AlarmClock" },
  { icon: AlarmClockCheck, name: "AlarmClockCheck" },
  { icon: Apple, name: "Apple" },
  { icon: Award, name: "Award" },
  { icon: Baby, name: "Baby" },
  { icon: BadgeDollarSign, name: "BadgeDollarSign" },
  { icon: BadgePoundSterling, name: "BadgePoundSterling" },
  { icon: BicepsFlexed, name: "BicepsFlexed" },
  { icon: Bike, name: "Bike" },
  { icon: Book, name: "Book" },
  { icon: BookA, name: "BookA" },
  { icon: BookOpen, name: "BookOpen" },
  { icon: Brain, name: "Brain" },
  { icon: Brush, name: "Brush" },
  { icon: Camera, name: "Camera" },
  { icon: Car, name: "Car" },
  { icon: CircleDollarSign, name: "CircleDollarSign" },
  { icon: CircleGauge, name: "CircleGauge" },
  { icon: Coffee, name: "Coffee" },
  { icon: Compass, name: "Compass" },
  { icon: Cookie, name: "Cookie" },
  { icon: Cpu, name: "Cpu" },
  { icon: Crown, name: "Crown" },
  { icon: CupSoda, name: "CupSoda" },
  { icon: Diamond, name: "Diamond" },
  { icon: DollarSign, name: "DollarSign" },
  { icon: Dumbbell, name: "Dumbbell" },
  { icon: Egg, name: "Egg" },
  { icon: Eye, name: "Eye" },
  { icon: Fish, name: "Fish" },
  { icon: Flag, name: "Flag" },
  { icon: Flame, name: "Flame" },
  { icon: FlameKindling, name: "FlameKindling" },
  { icon: Flask, name: "Flask" },
  { icon: Flower, name: "Flower" },
  { icon: Football, name: "Football" },
  { icon: Footprints, name: "Footprints" },
  { icon: Gamepad2, name: "Gamepad2" },
  { icon: Gift, name: "Gift" },
  { icon: GlassWater, name: "GlassWater" },
  { icon: Globe, name: "Globe" },
  { icon: Guitar, name: "Guitar" },
  { icon: Heart, name: "Heart" },
  { icon: Home, name: "Home" },
  { icon: Key, name: "Key" },
  { icon: Lamp, name: "Lamp" },
  { icon: LandPlot, name: "LandPlot" },
  { icon: Languages, name: "Languages" },
  { icon: Leaf, name: "Leaf" },
  { icon: Library, name: "Library" },
  { icon: Lightning, name: "Lightning" },
  { icon: Link, name: "Link" },
  { icon: Mail, name: "Mail" },
  { icon: Map, name: "Map" },
  { icon: Medal, name: "Medal" },
  { icon: Moon, name: "Moon" },
  { icon: Mountain, name: "Mountain" },
  { icon: Music, name: "Music" },
  { icon: Paint, name: "Paint" },
  { icon: Palette, name: "Palette" },
  { icon: Pen, name: "Pen" },
  { icon: PersonStanding, name: "PersonStanding" },
  { icon: Phone, name: "Phone" },
  { icon: Piano, name: "Piano" },
  { icon: Pizza, name: "Pizza" },
  { icon: Plane, name: "Plane" },
  { icon: Receipt, name: "Receipt" },
  { icon: ShowerHead, name: "ShowerHead" },
  { icon: Skull, name: "Skull" },
  { icon: Sprout, name: "Sprout" },
  { icon: TreeDeciduous, name: "TreeDeciduous" },
  { icon: TreePalm, name: "TreePalm" },
  { icon: TreePine, name: "TreePine" },
  { icon: Trees, name: "Trees" },
  { icon: Trophy, name: "Trophy" },
  { icon: Wallet, name: "Wallet" },
  { icon: Wind, name: "Wind" },
];

export const habitColors = [
  { name: "Red", value: "#ef4444" },
  { name: "Orange", value: "#f97316" },
  { name: "Amber", value: "#f59e0b" },
  { name: "Yellow", value: "#eab308" },
  { name: "Lime", value: "#84cc16" },
  { name: "Green", value: "#22c55e" },
  { name: "Emerald", value: "#10b981" },
  { name: "Teal", value: "#14b8a6" },
  { name: "Cyan", value: "#06b6d4" },
  { name: "Sky", value: "#0ea5e9" },
  { name: "Blue", value: "#3b82f6" },
  { name: "Indigo", value: "#6366f1" },
  { name: "Violet", value: "#8b5cf6" },
  { name: "Purple", value: "#a855f7" },
  { name: "Fuchsia", value: "#d946ef" },
  { name: "Pink", value: "#ec4899" },
  { name: "Rose", value: "#f43f5e" },
  { name: "Slate", value: "#64748b" },
  { name: "Gray", value: "#6b7280" },
  { name: "Zinc", value: "#71717a" },
];

export const habitCategories = [
  "Health & Fitness",
  "Personal Development",
  "Work",
  "Relationships",
  "Hobbies",
  "Creativity",
  "Finance",
  "Mental Wellbeing",
  "Education",
  "Home & Organization",
  "Social & Community",
];
